resources:
- bases/manager.yaml
- bases/service_account.yaml
- bases/config.yaml
- ../../crd
#  - ../../base
#  - config.yaml
- ../../rbac/namespace
#  - role.yaml
#  - role_binding.yaml

# Add the patch
patches:
  - path: patch-add-env-var-watch-namespace.yaml
